services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --no-input && gunicorn --bind 0.0.0.0:8000 twitter_app.wsgi:application --log-level debug"
    volumes:
      - .:/app
      - ./app/static:/app/static
      - ./app/media:/app/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/static
      - ./app/media:/app/media
      - C:/Users/macie/PycharmProjects/OchronaDanychProj/karabin.crt:/etc/nginx/ssl/localhost.crt
      - C:/Users/macie/PycharmProjects/OchronaDanychProj/karabin.key:/etc/nginx/ssl/localhost.key
    depends_on:
      - web