services:
  web:
    build: .
    command: >-
      sh -c "mkdir -p /certs &&
      openssl req -x509 -newkey rsa:4096 -nodes -keyout /certs/key.pem -out /certs/cert.pem -days 365 -subj '/CN=PW' &&
      python manage.py collectstatic --no-input &&
      python manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000 twitter_app.wsgi:application --log-level debug"
    volumes:
      - .:/app
      - ./app/static:/app/static
      - ./app/media:/app/media
      - ./certs:/certs
    environment:
      - SECRET_KEY
      - TOTP_ENCRYPTION_KEY
    healthcheck:
      test: ["CMD", "sh", "-c", "test -f /certs/cert.pem && test -f /certs/key.pem"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/static
      - ./app/media:/app/media
      - ./certs:/etc/nginx/ssl
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "https://localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3